name: 'docker build'
description: 'BE'
inputs:
  app-path:
    description: 'path of service to build'
    # required: true
    # default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  # ToDo: update path to dockerfile in app dir
  image: ${{ inputs.app-path }}/Dockerfile
  working-directory: ${{ inputs.app-path }}
  # args:
  #   - ${{ inputs.app-path }}