name: build service img
description: "build service img"

runs:
  using: composite
  steps:
    - uses: docker/setup-buildx-action@v3
    - run: docker build .
      working-directory: ${{ inputs.service_path }}
      shell: sh