name: 'docker build'
description: 'BE'
inputs:
  who-to-greet: # id
    description: 'who to greet'
    required: true
    default: 'dana'
  app-path: # id
    description: 'path of service to build'
    # required: true
    # default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.app-path }}