on: [push]

jobs:
  build-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PSWD }}

      - name: Build & push be
        # uses: docker/build-push-action@v5
        # with:
        #   push: true
        #   tags: ${{ secrets.DOCKERHUB_USER }}/s4e-be:v0.0.1
          
      # Action call
        uses: ./.github/actions/composite/be
        with:
          app-path: apps/be
          be-image-tag: ${{ secrets.DOCKERHUB_USER }}/s4e-be:v0.0.1
