on: [push]

# ToDo: learn labels
  # label:
  #   types:
  #     - created

jobs:
  build-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PSWD }}

      - name: Build & push be
        uses: ./.github/actions/composite/be
        with:
          app-path: apps/be
          be-image-tag: 's4e-be:v0.0.1'
