on: #[push]
  push:
    branches:
      - 'not-existing-branch'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-service
        id: build
        with:
          service_path: my-app