on: push

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PSWD: ${{ secrets.DOCKERHUB_PSWD }}
      run: |
        echo $DOCKERHUB_USER >> secrets.txt
        echo $DOCKERHUB_PSWD >> secrets.txt
        cat secrets.txt