on: #push
  # ToDo: learn labels
  label:
    types:
      - created

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    
    steps:
    - name: Play with outputs
      id: step1
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      run: |
        echo "test=hello" >> "$GITHUB_OUTPUT"
        echo $DOCKERHUB_USER >> "$GITHUB_OUTPUT"
        cat secrets.txt >> "$GITHUB_OUTPUT"
    
    - name: Play with outputs
      id: step2
      env:
        OUTPUT1: ${{needs.job1.outputs.output1}}
      run: echo "$OUTPUT1"