on: push

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      run: |
        echo "$env:DOCKERHUB_USER"
        echo $DOCKERHUB_USER >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2